// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://nyanpass.io/terms",
        "contact": {
            "name": "API Support",
            "url": "https://nyanpass.io/support",
            "email": "support@nyanpass.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/announcements": {
            "get": {
                "tags": [
                    "Admin/Announcement"
                ],
                "summary": "获取所有公告（包含草稿）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin/Announcement"
                ],
                "summary": "创建公告（管理员）",
                "parameters": [
                    {
                        "description": "公告信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateAnnouncementRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/announcements/{id}": {
            "get": {
                "tags": [
                    "Admin/Announcement"
                ],
                "summary": "获取公告详情（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin/Announcement"
                ],
                "summary": "更新公告（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "公告信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateAnnouncementRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Admin/Announcement"
                ],
                "summary": "删除公告（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/announcements/{id}/offline": {
            "post": {
                "tags": [
                    "Admin/Announcement"
                ],
                "summary": "下线公告（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/announcements/{id}/publish": {
            "post": {
                "tags": [
                    "Admin/Announcement"
                ],
                "summary": "发布公告（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/nodes": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin/Node"
                ],
                "summary": "添加节点（管理员）",
                "parameters": [
                    {
                        "description": "节点信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.AddNodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/nodes/{id}": {
            "get": {
                "tags": [
                    "Admin/Node"
                ],
                "summary": "获取节点详情（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "节点ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin/Node"
                ],
                "summary": "更新节点（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "节点ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "节点信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateNodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Admin/Node"
                ],
                "summary": "删除节点（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "节点ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/nodes/{id}/ping": {
            "post": {
                "tags": [
                    "Admin/Node"
                ],
                "summary": "测试节点连接（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "节点ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/nodes/{id}/refresh": {
            "post": {
                "tags": [
                    "Admin/Node"
                ],
                "summary": "刷新节点状态（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "节点ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/orders": {
            "get": {
                "tags": [
                    "Admin/Order"
                ],
                "summary": "获取订单列表（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "订单状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/orders/{id}": {
            "get": {
                "tags": [
                    "Admin/Order"
                ],
                "summary": "获取订单详情（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Admin/Order"
                ],
                "summary": "删除订单（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/orders/{id}/paid": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin/Order"
                ],
                "summary": "标记订单已支付（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "支付方式",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.MarkPaidRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/orders/{id}/refund": {
            "post": {
                "tags": [
                    "Admin/Order"
                ],
                "summary": "退款（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/plans": {
            "get": {
                "tags": [
                    "Admin/Plan"
                ],
                "summary": "获取所有套餐列表（包含隐藏）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin/Plan"
                ],
                "summary": "创建新套餐",
                "parameters": [
                    {
                        "description": "套餐信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreatePlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/plans/{id}": {
            "get": {
                "tags": [
                    "Admin/Plan"
                ],
                "summary": "获取套餐详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "套餐ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin/Plan"
                ],
                "summary": "更新套餐",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "套餐ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "套餐信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdatePlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Admin/Plan"
                ],
                "summary": "删除套餐",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "套餐ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/settings": {
            "get": {
                "tags": [
                    "Admin/Setting"
                ],
                "summary": "获取所有设置（管理员）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin/Setting"
                ],
                "summary": "设置单个值（管理员）",
                "parameters": [
                    {
                        "description": "设置信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/settings/batch": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin/Setting"
                ],
                "summary": "批量更新设置（管理员）",
                "parameters": [
                    {
                        "description": "设置列表",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.BatchUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/settings/group/{group}": {
            "get": {
                "tags": [
                    "Admin/Setting"
                ],
                "summary": "获取指定分组的设置（管理员）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分组名称",
                        "name": "group",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/settings/{key}": {
            "delete": {
                "tags": [
                    "Admin/Setting"
                ],
                "summary": "删除设置（管理员）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设置键名",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users": {
            "get": {
                "tags": [
                    "Admin/User"
                ],
                "summary": "获取用户列表（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}": {
            "get": {
                "tags": [
                    "Admin/User"
                ],
                "summary": "获取用户详情（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin/User"
                ],
                "summary": "更新用户（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "用户信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.AdminUpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Admin/User"
                ],
                "summary": "删除用户（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}/ban": {
            "post": {
                "tags": [
                    "Admin/User"
                ],
                "summary": "禁用用户（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}/charge": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Admin/User"
                ],
                "summary": "用户充值（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "充值金额",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ChargeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}/reset-traffic": {
            "post": {
                "tags": [
                    "Admin/User"
                ],
                "summary": "重置用户流量（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/users/{id}/unban": {
            "post": {
                "tags": [
                    "Admin/User"
                ],
                "summary": "解禁用户（管理员）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/announcements": {
            "get": {
                "tags": [
                    "Announcement"
                ],
                "summary": "获取已发布公告",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/announcements/popup": {
            "get": {
                "tags": [
                    "Announcement"
                ],
                "summary": "获取需要弹窗的公告",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/nodes": {
            "get": {
                "tags": [
                    "Node"
                ],
                "summary": "获取节点列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/plans": {
            "get": {
                "tags": [
                    "Plan"
                ],
                "summary": "获取可见套餐列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/settings": {
            "get": {
                "tags": [
                    "Setting"
                ],
                "summary": "获取公开设置（站点名称、描述等）",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/orders": {
            "get": {
                "tags": [
                    "Order"
                ],
                "summary": "获取我的订单列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "创建订单",
                "parameters": [
                    {
                        "description": "订单信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/orders/{id}": {
            "get": {
                "tags": [
                    "Order"
                ],
                "summary": "获取订单详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/orders/{id}/cancel": {
            "post": {
                "tags": [
                    "Order"
                ],
                "summary": "取消订单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "订单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/password": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "description": "密码信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/profile": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/subscribe/reset": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "重置订阅令牌",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/traffic": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "获取流量统计",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "使用邮箱和密码登录，获取 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/service.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "登录失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "注册新用户账户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "注册失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/client/subscribe/{token}": {
            "get": {
                "description": "根据用户 UUID Token 获取订阅链接，支持多种客户端格式",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Subscribe"
                ],
                "summary": "获取订阅配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户订阅 Token (UUID)",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "订阅配置内容",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "缺少 Token",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ChargeRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                }
            }
        },
        "handler.MarkPaidRequest": {
            "type": "object",
            "required": [
                "pay_method"
            ],
            "properties": {
                "pay_method": {
                    "type": "string"
                }
            }
        },
        "handler.SetRequest": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "balance": {
                    "description": "资产信息",
                    "type": "number"
                },
                "commission": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "download": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "expired_at": {
                    "type": "string"
                },
                "group_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "invite_code": {
                    "description": "邀请系统",
                    "type": "string"
                },
                "invited_by": {
                    "type": "integer"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "last_login_at": {
                    "description": "系统信息",
                    "type": "string"
                },
                "last_login_ip": {
                    "type": "string"
                },
                "status": {
                    "description": "状态与权限",
                    "type": "integer"
                },
                "telegram_id": {
                    "description": "第三方绑定",
                    "type": "integer"
                },
                "transfer_enable": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "upload": {
                    "description": "流量控制 (单位: Bytes)",
                    "type": "integer"
                },
                "uuid": {
                    "description": "订阅唯一标识 (SQLite兼容)",
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "提示信息",
                    "type": "string"
                }
            }
        },
        "service.AddNodeRequest": {
            "type": "object",
            "required": [
                "address",
                "api_port",
                "api_token",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "api_port": {
                    "type": "integer"
                },
                "api_token": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "rate": {
                    "type": "number",
                    "minimum": 0
                },
                "region": {
                    "type": "string"
                }
            }
        },
        "service.AdminUpdateUserRequest": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "commission": {
                    "type": "number"
                },
                "download": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "expired_at": {
                    "type": "string"
                },
                "group_id": {
                    "type": "integer"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "transfer_enable": {
                    "type": "integer"
                },
                "upload": {
                    "type": "integer"
                }
            }
        },
        "service.BatchUpdateRequest": {
            "type": "object",
            "required": [
                "settings"
            ],
            "properties": {
                "settings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.SettingItem"
                    }
                }
            }
        },
        "service.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 6
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "service.CreateAnnouncementRequest": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "expired_at": {
                    "type": "string"
                },
                "popup": {
                    "type": "boolean"
                },
                "priority": {
                    "type": "integer"
                },
                "published_at": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "tags": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "service.CreateOrderRequest": {
            "type": "object",
            "required": [
                "plan_id"
            ],
            "properties": {
                "coupon_id": {
                    "type": "integer"
                },
                "plan_id": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string"
                }
            }
        },
        "service.CreatePlanRequest": {
            "type": "object",
            "required": [
                "duration",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "device_limit": {
                    "description": "设备数限制",
                    "type": "integer",
                    "minimum": 0
                },
                "duration": {
                    "description": "有效期(天)",
                    "type": "integer"
                },
                "group_id": {
                    "description": "用户组",
                    "type": "integer"
                },
                "hidden": {
                    "description": "是否隐藏",
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number",
                    "minimum": 0
                },
                "sort": {
                    "description": "排序权重",
                    "type": "integer"
                },
                "speed_limit": {
                    "description": "速度限制(Mbps)",
                    "type": "integer",
                    "minimum": 0
                },
                "transfer": {
                    "description": "流量限制(GB)",
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "service.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "service.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "service.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "invite_code": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "service.SettingItem": {
            "type": "object",
            "required": [
                "key"
            ],
            "properties": {
                "desc": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "service.UpdateAnnouncementRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "expired_at": {
                    "type": "string"
                },
                "popup": {
                    "type": "boolean"
                },
                "priority": {
                    "type": "integer"
                },
                "published_at": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "tags": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "service.UpdateNodeRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "api_port": {
                    "type": "integer"
                },
                "api_token": {
                    "type": "string"
                },
                "carrier": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "insecure": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "rate": {
                    "type": "number"
                },
                "region": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "service.UpdatePlanRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "device_limit": {
                    "type": "integer",
                    "minimum": 0
                },
                "duration": {
                    "type": "integer"
                },
                "group_id": {
                    "type": "integer"
                },
                "hidden": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number",
                    "minimum": 0
                },
                "sort": {
                    "type": "integer"
                },
                "speed_limit": {
                    "type": "integer",
                    "minimum": 0
                },
                "transfer": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT Token 认证，格式：Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "NyanPass API",
	Description:      "NyanPass 高性能中转面板 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
